
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Brushes
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Bundled
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Effects
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/FileTypes
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Bundled/AvifFileType
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Bundled/DDSFileTypePlus
mkdir %DOWNLOAD_DIR%/win/files/pdn_ext/Bundled/WebPFileType
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush01.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush01.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush02.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush02.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush03.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush03.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush04.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush04.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush05.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush05.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush06.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush06.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush07.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush07.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush08.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush08.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush09.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush09.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush10.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush10.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush11.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush11.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush12.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush12.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush13.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush13.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush14.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush14.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush15.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush15.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/brush16.png" "%REMOTE_URL%/win/files/pdn_ext/Brushes/brush16.png"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/Ink PS Brushes.abr" "%REMOTE_URL%/win/files/pdn_ext/Brushes/Ink PS Brushes.abr"
curl -O "%PDN_DIR%/win/files/pdn_ext/Brushes/ink stoke brush by freeject.net.abr" "%REMOTE_URL%/win/files/pdn_ext/Brushes/ink stoke brush by freeject.net.abr"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/AvifFileType/AvifFileType.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/AvifFileType/AvifFileType.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/AvifFileType/AvifNative_x64.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/AvifFileType/AvifNative_x64.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/AvifFileType/License.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/AvifFileType/License.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/AvifFileType/Readme.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/AvifFileType/Readme.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/AvifFileType/Third Party Notices.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/AvifFileType/Third Party Notices.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/DDSFileTypePlus/DdsFileTypePlus.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/DDSFileTypePlus/DdsFileTypePlus.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/DDSFileTypePlus/DdsFileTypePlusIO_x64.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/DDSFileTypePlus/DdsFileTypePlusIO_x64.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/DDSFileTypePlus/License.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/DDSFileTypePlus/License.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/DDSFileTypePlus/Readme.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/DDSFileTypePlus/Readme.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/WebPFileType/License.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/WebPFileType/License.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/WebPFileType/Readme.txt" "%REMOTE_URL%/win/files/pdn_ext/Bundled/WebPFileType/Readme.txt"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/WebPFileType/WebP_x64.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/WebPFileType/WebP_x64.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Bundled/WebPFileType/WebPFileType.dll" "%REMOTE_URL%/win/files/pdn_ext/Bundled/WebPFileType/WebPFileType.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/AA's_Assistant.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/AA's_Assistant.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Alpha_to_0.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Alpha_to_0.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Alpha_to_255.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Alpha_to_255.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/AlphaMask.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/AlphaMask.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Anti-Alias by jsonchiu.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Anti-Alias by jsonchiu.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Bars.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Bars.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/BlackandAlpha+.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/BlackandAlpha+.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Borders N' Shapes.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Borders N' Shapes.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/BrushFactory.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/BrushFactory.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/CK_Plugin.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/CK_Plugin.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Color Match.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Color Match.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/coloraberation.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/coloraberation.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/ColorZoomBlur.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/ColorZoomBlur.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Curves+.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Curves+.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Displacement.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Displacement.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/dpyColorBalance.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/dpyColorBalance.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Dull.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Dull.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Film.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Film.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Gradient Blocks.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Gradient Blocks.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Gradient Mapping.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Gradient Mapping.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/GradientBlur.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/GradientBlur.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/GrayScale+.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/GrayScale+.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Grid Warp.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Grid Warp.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Jitter.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Jitter.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/LightRays.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/LightRays.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Liquify.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Liquify.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/ListOfPalettes.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/ListOfPalettes.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Magnifier.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Magnifier.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Metallize.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Metallize.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/MultiThreshold.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/MultiThreshold.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Outline Object.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Outline Object.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Perspective.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Perspective.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Pixelate+.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Pixelate+.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/pxEexpansion.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/pxEexpansion.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/ScriptLab.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/ScriptLab.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/SeamlessHelper.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/SeamlessHelper.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/SimulateColorDepth.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/SimulateColorDepth.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/SmoothNoise.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/SmoothNoise.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Smudge.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Smudge.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Splatter.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Splatter.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/Effects/Trail.dll" "%REMOTE_URL%/win/files/pdn_ext/Effects/Trail.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/AnimGIF.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/AnimGIF.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/BmpX.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/BmpX.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/BmpX.pdb" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/BmpX.pdb"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/IcoCur.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/IcoCur.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/PhotoShop.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/PhotoShop.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/VtfFileType.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/VtfFileType.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/VTFLib.x64.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/VTFLib.x64.dll"
curl -O "%PDN_DIR%/win/files/pdn_ext/FileTypes/VTFLib.x86.dll" "%REMOTE_URL%/win/files/pdn_ext/FileTypes/VTFLib.x86.dll"
